documentation:
- "**/*.md"
- "*.md"

workflow:
- any: ['.github/*']

config:
- "*.yml"
- "**/*.yml"
- "*.properties"

haveTests: 
- any: ['src/test/*.kt']

leetcode: 
- **/leetcode/**/*

hackerank:
- any: ['**/hackerrank_prep/**/*']
