leetcode: 
- src/**/leetcode/**/*

hackerank:
- any: ['src/**/hackerrank_prep/**/*']

documentation:
- "**/*.md"
- "*.md"

workflow:
- any: ['.github/*']

config:
- "*.yml"
- "**/*.yml"
- "*.properties"

haveTests: 
- any: ['src/test/*.kt']


